site_name: Remediário

repo_name: "2023.1-Remediário"
repo_url: "https://github.com/mdsreq-fga-unb/2023.1-Remediario"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.section
    - navigation.path
    - navigation.top
    - tabs
  language: pt-BR
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      accent: lime

nav:
  - Home: index.md
  - Documentação de Atividades:
      - Apresentações:
          - Seminários:
              - Apresentação do problema: "documentacao/Seminarios/Apresentacao1.md"
              - Diagrama de Ishikawa: "documentacao/Seminarios/Apresentacao2.md"
              - SAFe Scrum: "documentacao/Seminarios/Apresentacao3.md"
          - Unidades:
              - Unidade 1: "documentacao/Unidades/Unidade1.md"
              - Unidade 2: "documentacao/Unidades/Unidade2.md"
              - Unidade 3: "documentacao/Unidades/Unidade3.md"
              - Unidade 4: "documentacao/Unidades/Unidade4.md"
      - Reuniões de Sprints:
          - Sprint 1: "documentacao/Reuniões de Sprints/Sprint1.md"
          - Sprint 2: "documentacao/Reuniões de Sprints/Sprint2.md"
          - Sprint 3: "documentacao/Reuniões de Sprints/Sprint3.md"
          - Sprint 4: "documentacao/Reuniões de Sprints/Sprint4.md"
          - Sprint 5: "documentacao/Reuniões de Sprints/Sprint5.md"
          - Sprint 6: "documentacao/Reuniões de Sprints/Sprint6.md"
          - Sprint 7: "documentacao/Reuniões de Sprints/Sprint7.md"
          - Sprint 8: "documentacao/Reuniões de Sprints/Sprint8.md"
          - Sprint 9: "documentacao/Reuniões de Sprints/Sprint9.md"
          - Sprint 10: "documentacao/Reuniões de Sprints/Sprint10.md"
          - Sprint 11: "documentacao/Reuniões de Sprints/Sprint11.md"

  - Entregas:
      - Unidade 1:
          - Visão Geral do Produto: "entregas/unidade1/VisaoProdutoProjeto.md"
      - Unidade 2:
          - Backlog do Produto: "entregas/unidade2/Backlog.md"
          - Mural de requisitos: "entregas/unidade2/Mural.md"
      - Unidade 3:
          - MVP 1: "entregas/unidade3/MVP1.md"
          - PBB: "entregas/unidade3/PBB.md"
          - SaFE: "entregas/unidade3/SaFE.md"
          - BDD: "entregas/unidade3/BDD.md"
      - Unidade 4:
          - MVP 2: "entregas/unidade4/MVP2.md"
          - Casos de Uso: "entregas/unidade4/CasosdeUso.md"
          - USM: "entregas/unidade4/USM.md"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mdsreq-fga-unb/2023.1-Remediario
  footer: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - attr_list
  - md_in_html
  - def_list
