site_name: MedicaCerto

repo_name: "2023.1-MedicaCerto"
repo_url: "https://github.com/mdsreq-fga-unb/2023.1-MedicaCerto"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.section
    - navigation.path
    - navigation.top
    - tabs
  language: pt-BR
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      accent: lime

nav:
  - Home: index.md
  - Documentação de Atividades:
      - Apresentações:
          - 1ª apresentação: "documentacao/Apresentacao/Apresentacao1.md"
          - 2ª apresentação: "documentacao/Apresentacao/Apresentacao2.md"
          - 3ª apresentação: "documentacao/Apresentacao/Apresentacao3.md"
      - Reuniões de Sprints:
          - Sprint 1: "documentacao/Reuniões de Sprints/Sprint1.md"
          - Sprint 2: "documentacao/Reuniões de Sprints/Sprint2.md"
          - Sprint 3: "documentacao/Reuniões de Sprints/Sprint3.md"
          - Sprint 4: "documentacao/Reuniões de Sprints/Sprint4.md"
          - Sprint 5: "documentacao/Reuniões de Sprints/Sprint5.md"
          - Sprint 6: "documentacao/Reuniões de Sprints/Sprint6.md"

  - Entregas:
      - Unidade 1:
          - Visão Geral do Produto: "entregas/unidade1/VisaoProdutoProjeto.md"
      - Unidade 2:
          - Backlog do Produto: "entregas/unidade2/Backlog.md"
          - Mural de requisitos: "entregas/unidade2/Mural.md"
          - Apresentação da Unidade 2: "entregas/unidade2/Apresentacao.md"
      - Unidade 3:
          - Apresentação da Unidade 3: "entregas/unidade3/Apresentacao.md"
          - PBB: "entregas/unidade3/PBB.md"
          - SaFE: "entregas/unidade3/SaFE.md"
          

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mdsreq-fga-unb/2023.1-MedicaCerto
  footer: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - attr_list
  - md_in_html
  - def_list
