site_name: Remediario

repo_name: "2023.1-Remediario"
repo_url: "https://github.com/mdsreq-fga-unb/2023.1-Remediario"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.section
    - navigation.path
    - navigation.top
    - tabs
  language: pt-BR
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      accent: lime

nav:
  - Home: index.md
  - Documentação de Atividades:
      - Apresentações:
          - 1ª apresentação: "documentacao/Apresentacao/Apresentacao1.md"
          - 2ª apresentação: "documentacao/Apresentacao/Apresentacao2.md"
          - 3ª apresentação: "documentacao/Apresentacao/Apresentacao3.md"
      - Sprints:
          - Sprint 0: "documentacao/Sprints/Sprint0.md"
          - Sprint 1: "documentacao/Sprints/Sprint1.md"
          - Sprint 2: "documentacao/Sprints/Sprint2.md"
          - Sprint 3: "documentacao/Sprints/Sprint3.md"
  - Entregas:
      - Unidade 1:
          - Visão Geral do Produto: "entregas/unidade1/VisaoProdutoProjeto.md"
      - Unidade 2:
          - Backlog do Produto: "entregas/unidade2/Backlog.md"
          - Mural do projeto: "entregas/unidade2/Mural.md"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mdsreq-fga-unb/2023.1-Remediario
  footer: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - attr_list
  - md_in_html
  - def_list
